# Generated by Django 3.1.3 on 2020-11-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_fees',
            field=models.IntegerField(default=500),
        ),
    ]
