# Generated by Django 3.1.3 on 2020-11-04 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201104_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_thumbnail',
        ),
    ]
