# Generated by Django 3.1.3 on 2020-11-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_student_student_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='student_firstname',
        ),
        migrations.AddField(
            model_name='student',
            name='student_lastname',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
